In [1]:
import numpy as np 
import pandas as pd
import sys
sys.path.append(r"C:\Users\User\Downloads\film\Credit-Scoring-Model-for-Consumer-Loans-in-Banking\src")
from feature_engineering import (extract_date_features,create_aggregate_features,strip,one_hot_encode,normalize,standardize,apply_woe,calculate_rfms)

In [2]:
data=pd.read_csv("../data/data.csv")

In [3]:
data.head()

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,CurrencyCode,CountryCode,ProviderId,ProductId,ProductCategory,ChannelId,Amount,Value,TransactionStartTime,PricingStrategy,FraudResult
0,TransactionId_76871,BatchId_36123,AccountId_3957,SubscriptionId_887,CustomerId_4406,UGX,256,ProviderId_6,ProductId_10,airtime,ChannelId_3,1000.0,1000,2018-11-15T02:18:49Z,2,0
1,TransactionId_73770,BatchId_15642,AccountId_4841,SubscriptionId_3829,CustomerId_4406,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-20.0,20,2018-11-15T02:19:08Z,2,0
2,TransactionId_26203,BatchId_53941,AccountId_4229,SubscriptionId_222,CustomerId_4683,UGX,256,ProviderId_6,ProductId_1,airtime,ChannelId_3,500.0,500,2018-11-15T02:44:21Z,2,0
3,TransactionId_380,BatchId_102363,AccountId_648,SubscriptionId_2185,CustomerId_988,UGX,256,ProviderId_1,ProductId_21,utility_bill,ChannelId_3,20000.0,21800,2018-11-15T03:32:55Z,2,0
4,TransactionId_28195,BatchId_38780,AccountId_4841,SubscriptionId_3829,CustomerId_988,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-644.0,644,2018-11-15T03:34:21Z,2,0

In [4]:
create_aggregate_features(data,"CustomerId","Amount")

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,CurrencyCode,CountryCode,ProviderId,ProductId,ProductCategory,ChannelId,Amount,Value,TransactionStartTime,PricingStrategy,FraudResult,total_transaction_amount,average_transaction_amount,transaction_count,transaction_stddev
0,TransactionId_76871,BatchId_36123,AccountId_3957,SubscriptionId_887,CustomerId_4406,UGX,256,ProviderId_6,ProductId_10,airtime,ChannelId_3,1000.0,1000,2018-11-15T02:18:49Z,2,0,109921.75,923.712185,119,3042.294251
1,TransactionId_73770,BatchId_15642,AccountId_4841,SubscriptionId_3829,CustomerId_4406,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-20.0,20,2018-11-15T02:19:08Z,2,0,109921.75,923.712185,119,3042.294251
2,TransactionId_26203,BatchId_53941,AccountId_4229,SubscriptionId_222,CustomerId_4683,UGX,256,ProviderId_6,ProductId_1,airtime,ChannelId_3,500.0,500,2018-11-15T02:44:21Z,2,0,1000.00,500.000000,2,0.000000
3,TransactionId_380,BatchId_102363,AccountId_648,SubscriptionId_2185,CustomerId_988,UGX,256,ProviderId_1,ProductId_21,utility_bill,ChannelId_3,20000.0,21800,2018-11-15T03:32:55Z,2,0,228727.20,6019.136842,38,17169.241610
4,TransactionId_28195,BatchId_38780,AccountId_4841,SubscriptionId_3829,CustomerId_988,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-644.0,644,2018-11-15T03:34:21Z,2,0,228727.20,6019.136842,38,17169.241610
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95657,TransactionId_89881,BatchId_96668,AccountId_4841,SubscriptionId_3829,CustomerId_3078,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-1000.0,1000,2019-02-13T09:54:09Z,2,0,2438140.00,4255.043630,573,22554.029939
95658,TransactionId_91597,BatchId_3503,AccountId_3439,SubscriptionId_2643,CustomerId_3874,UGX,256,ProviderId_6,ProductId_10,airtime,ChannelId_3,1000.0,1000,2019-02-13T09:54:25Z,2,0,58499.60,1360.455814,43,2274.756582
95659,TransactionId_82501,BatchId_118602,AccountId_4841,SubscriptionId_3829,CustomerId_3874,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-20.0,20,2019-02-13T09:54:35Z,2,0,58499.60,1360.455814,43,2274.756582
95660,TransactionId_136354,BatchId_70924,AccountId_1346,SubscriptionId_652,CustomerId_1709,UGX,256,ProviderId_6,ProductId_19,tv,ChannelId_3,3000.0,3000,2019-02-13T10:01:10Z,2,0,851985.00,1625.925573,524,3207.920536
95661,TransactionId_35670,BatchId_29317,AccountId_4841,SubscriptionId_3829,CustomerId_1709,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-60.0,60,2019-02-13T10:01:28Z,2,0,851985.00,1625.925573,524,3207.920536

In [5]:
data=create_aggregate_features(data,"CustomerId","Amount")

In [6]:
data

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,CurrencyCode,CountryCode,ProviderId,ProductId,ProductCategory,ChannelId,Amount,Value,TransactionStartTime,PricingStrategy,FraudResult,total_transaction_amount,average_transaction_amount,transaction_count,transaction_stddev
0,TransactionId_76871,BatchId_36123,AccountId_3957,SubscriptionId_887,CustomerId_4406,UGX,256,ProviderId_6,ProductId_10,airtime,ChannelId_3,1000.0,1000,2018-11-15T02:18:49Z,2,0,109921.75,923.712185,119,3042.294251
1,TransactionId_73770,BatchId_15642,AccountId_4841,SubscriptionId_3829,CustomerId_4406,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-20.0,20,2018-11-15T02:19:08Z,2,0,109921.75,923.712185,119,3042.294251
2,TransactionId_26203,BatchId_53941,AccountId_4229,SubscriptionId_222,CustomerId_4683,UGX,256,ProviderId_6,ProductId_1,airtime,ChannelId_3,500.0,500,2018-11-15T02:44:21Z,2,0,1000.00,500.000000,2,0.000000
3,TransactionId_380,BatchId_102363,AccountId_648,SubscriptionId_2185,CustomerId_988,UGX,256,ProviderId_1,ProductId_21,utility_bill,ChannelId_3,20000.0,21800,2018-11-15T03:32:55Z,2,0,228727.20,6019.136842,38,17169.241610
4,TransactionId_28195,BatchId_38780,AccountId_4841,SubscriptionId_3829,CustomerId_988,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-644.0,644,2018-11-15T03:34:21Z,2,0,228727.20,6019.136842,38,17169.241610
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95657,TransactionId_89881,BatchId_96668,AccountId_4841,SubscriptionId_3829,CustomerId_3078,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-1000.0,1000,2019-02-13T09:54:09Z,2,0,2438140.00,4255.043630,573,22554.029939
95658,TransactionId_91597,BatchId_3503,AccountId_3439,SubscriptionId_2643,CustomerId_3874,UGX,256,ProviderId_6,ProductId_10,airtime,ChannelId_3,1000.0,1000,2019-02-13T09:54:25Z,2,0,58499.60,1360.455814,43,2274.756582
95659,TransactionId_82501,BatchId_118602,AccountId_4841,SubscriptionId_3829,CustomerId_3874,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-20.0,20,2019-02-13T09:54:35Z,2,0,58499.60,1360.455814,43,2274.756582
95660,TransactionId_136354,BatchId_70924,AccountId_1346,SubscriptionId_652,CustomerId_1709,UGX,256,ProviderId_6,ProductId_19,tv,ChannelId_3,3000.0,3000,2019-02-13T10:01:10Z,2,0,851985.00,1625.925573,524,3207.920536
95661,TransactionId_35670,BatchId_29317,AccountId_4841,SubscriptionId_3829,CustomerId_1709,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-60.0,60,2019-02-13T10:01:28Z,2,0,851985.00,1625.925573,524,3207.920536

In [7]:
data=data.drop(columns="CurrencyCode",axis=1)

In [8]:
extract_date_features(data,"TransactionStartTime")

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,CountryCode,ProviderId,ProductId,ProductCategory,ChannelId,...,PricingStrategy,FraudResult,total_transaction_amount,average_transaction_amount,transaction_count,transaction_stddev,transaction_hour,transaction_day,transaction_month,transaction_year
0,TransactionId_76871,BatchId_36123,AccountId_3957,SubscriptionId_887,CustomerId_4406,256,ProviderId_6,ProductId_10,airtime,ChannelId_3,...,2,0,109921.75,923.712185,119,3042.294251,2,15,11,2018
1,TransactionId_73770,BatchId_15642,AccountId_4841,SubscriptionId_3829,CustomerId_4406,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,...,2,0,109921.75,923.712185,119,3042.294251,2,15,11,2018
2,TransactionId_26203,BatchId_53941,AccountId_4229,SubscriptionId_222,CustomerId_4683,256,ProviderId_6,ProductId_1,airtime,ChannelId_3,...,2,0,1000.00,500.000000,2,0.000000,2,15,11,2018
3,TransactionId_380,BatchId_102363,AccountId_648,SubscriptionId_2185,CustomerId_988,256,ProviderId_1,ProductId_21,utility_bill,ChannelId_3,...,2,0,228727.20,6019.136842,38,17169.241610,3,15,11,2018
4,TransactionId_28195,BatchId_38780,AccountId_4841,SubscriptionId_3829,CustomerId_988,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,...,2,0,228727.20,6019.136842,38,17169.241610,3,15,11,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95657,TransactionId_89881,BatchId_96668,AccountId_4841,SubscriptionId_3829,CustomerId_3078,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,...,2,0,2438140.00,4255.043630,573,22554.029939,9,13,2,2019
95658,TransactionId_91597,BatchId_3503,AccountId_3439,SubscriptionId_2643,CustomerId_3874,256,ProviderId_6,ProductId_10,airtime,ChannelId_3,...,2,0,58499.60,1360.455814,43,2274.756582,9,13,2,2019
95659,TransactionId_82501,BatchId_118602,AccountId_4841,SubscriptionId_3829,CustomerId_3874,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,...,2,0,58499.60,1360.455814,43,2274.756582,9,13,2,2019
95660,TransactionId_136354,BatchId_70924,AccountId_1346,SubscriptionId_652,CustomerId_1709,256,ProviderId_6,ProductId_19,tv,ChannelId_3,...,2,0,851985.00,1625.925573,524,3207.920536,10,13,2,2019
95661,TransactionId_35670,BatchId_29317,AccountId_4841,SubscriptionId_3829,CustomerId_1709,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,...,2,0,851985.00,1625.925573,524,3207.920536,10,13,2,2019

In [9]:
strip(data)

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,CountryCode,ProviderId,ProductId,ProductCategory,ChannelId,...,PricingStrategy,FraudResult,total_transaction_amount,average_transaction_amount,transaction_count,transaction_stddev,transaction_hour,transaction_day,transaction_month,transaction_year
0,76871.0,36123.0,3957.0,887.0,4406.0,256,6.0,10.0,airtime,3.0,...,2,0,109921.75,923.712185,119,3042.294251,2,15,11,2018
1,73770.0,15642.0,4841.0,3829.0,4406.0,256,4.0,6.0,financial_services,2.0,...,2,0,109921.75,923.712185,119,3042.294251,2,15,11,2018
2,26203.0,53941.0,4229.0,222.0,4683.0,256,6.0,1.0,airtime,3.0,...,2,0,1000.00,500.000000,2,0.000000,2,15,11,2018
3,380.0,102363.0,648.0,2185.0,988.0,256,1.0,21.0,utility_bill,3.0,...,2,0,228727.20,6019.136842,38,17169.241610,3,15,11,2018
4,28195.0,38780.0,4841.0,3829.0,988.0,256,4.0,6.0,financial_services,2.0,...,2,0,228727.20,6019.136842,38,17169.241610,3,15,11,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95657,89881.0,96668.0,4841.0,3829.0,3078.0,256,4.0,6.0,financial_services,2.0,...,2,0,2438140.00,4255.043630,573,22554.029939,9,13,2,2019
95658,91597.0,3503.0,3439.0,2643.0,3874.0,256,6.0,10.0,airtime,3.0,...,2,0,58499.60,1360.455814,43,2274.756582,9,13,2,2019
95659,82501.0,118602.0,4841.0,3829.0,3874.0,256,4.0,6.0,financial_services,2.0,...,2,0,58499.60,1360.455814,43,2274.756582,9,13,2,2019
95660,136354.0,70924.0,1346.0,652.0,1709.0,256,6.0,19.0,tv,3.0,...,2,0,851985.00,1625.925573,524,3207.920536,10,13,2,2019
95661,35670.0,29317.0,4841.0,3829.0,1709.0,256,4.0,6.0,financial_services,2.0,...,2,0,851985.00,1625.925573,524,3207.920536,10,13,2,2019

In [10]:
data=one_hot_encode(data,["ProductCategory"])

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95662 entries, 0 to 95661
Data columns (total 31 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   TransactionId                       95662 non-null  float64
 1   BatchId                             95662 non-null  float64
 2   AccountId                           95662 non-null  float64
 3   SubscriptionId                      95662 non-null  float64
 4   CustomerId                          95662 non-null  float64
 5   CountryCode                         95662 non-null  int64
 6   ProviderId                          95662 non-null  float64
 7   ProductId                           95662 non-null  float64
 8   ChannelId                           95662 non-null  float64
 9   Amount                              95662 non-null  float64
 10  Value                               95662 non-null  int64
 11  TransactionStartTime                95662 non-null  datetime64[ns, UTC]
 12  PricingStrategy                     95662 non-null  int64
 13  FraudResult                         95662 non-null  int64
 14  total_transaction_amount            95662 non-null  float64
 15  average_transaction_amount          95662 non-null  float64
 16  transaction_count                   95662 non-null  int64
 17  transaction_stddev                  94950 non-null  float64
 18  transaction_hour                    95662 non-null  int32
 19  transaction_day                     95662 non-null  int32
 20  transaction_month                   95662 non-null  int32
 21  transaction_year                    95662 non-null  int32
 22  ProductCategory_airtime             95662 non-null  int64
 23  ProductCategory_data_bundles        95662 non-null  int64
 24  ProductCategory_financial_services  95662 non-null  int64
 25  ProductCategory_movies              95662 non-null  int64
 26  ProductCategory_other               95662 non-null  int64
 27  ProductCategory_ticket              95662 non-null  int64
 28  ProductCategory_transport           95662 non-null  int64
 29  ProductCategory_tv                  95662 non-null  int64
 30  ProductCategory_utility_bill        95662 non-null  int64
dtypes: datetime64[ns, UTC](1), float64(12), int32(4), int64(14)
memory usage: 21.2 MB

In [12]:
data.skew(numeric_only=True)

TransactionId                          -0.003532
BatchId                                -0.007066
AccountId                              -0.697127
SubscriptionId                         -0.820864
CustomerId                              0.436333
CountryCode                             0.000000
ProviderId                             -1.015381
ProductId                               1.018136
ChannelId                               0.353773
Amount                                 51.098490
Value                                  51.291086
PricingStrategy                         1.659057
FraudResult                            22.196295
total_transaction_amount               -4.160956
average_transaction_amount             76.009550
transaction_count                       3.399589
transaction_stddev                     14.197894
transaction_hour                       -0.091498
transaction_day                        -0.012952
transaction_month                      -0.013098
transaction_year                        0.011541
ProductCategory_airtime                 0.117450
ProductCategory_data_bundles            7.505052
ProductCategory_financial_services      0.101573
ProductCategory_movies                 23.316494
ProductCategory_other                 218.699566
ProductCategory_ticket                 20.973690
ProductCategory_transport              61.835266
ProductCategory_tv                      8.474088
ProductCategory_utility_bill            6.844407
dtype: float64

In [13]:
data.columns

Index(['TransactionId', 'BatchId', 'AccountId', 'SubscriptionId', 'CustomerId',
       'CountryCode', 'ProviderId', 'ProductId', 'ChannelId', 'Amount',
       'Value', 'TransactionStartTime', 'PricingStrategy', 'FraudResult',
       'total_transaction_amount', 'average_transaction_amount',
       'transaction_count', 'transaction_stddev', 'transaction_hour',
       'transaction_day', 'transaction_month', 'transaction_year',
       'ProductCategory_airtime', 'ProductCategory_data_bundles',
       'ProductCategory_financial_services', 'ProductCategory_movies',
       'ProductCategory_other', 'ProductCategory_ticket',
       'ProductCategory_transport', 'ProductCategory_tv',
       'ProductCategory_utility_bill'],
      dtype='object')

In [14]:
standardize(data, ["total_transaction_amount", 
    "average_transaction_amount"])

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,CountryCode,ProviderId,ProductId,ChannelId,Amount,...,transaction_year,ProductCategory_airtime,ProductCategory_data_bundles,ProductCategory_financial_services,ProductCategory_movies,ProductCategory_other,ProductCategory_ticket,ProductCategory_transport,ProductCategory_tv,ProductCategory_utility_bill
0,76871.0,36123.0,3957.0,887.0,4406.0,256,6.0,10.0,3.0,1000.0,...,2018,1,0,0,0,0,0,0,0,0
1,73770.0,15642.0,4841.0,3829.0,4406.0,256,4.0,6.0,2.0,-20.0,...,2018,0,0,1,0,0,0,0,0,0
2,26203.0,53941.0,4229.0,222.0,4683.0,256,6.0,1.0,3.0,500.0,...,2018,1,0,0,0,0,0,0,0,0
3,380.0,102363.0,648.0,2185.0,988.0,256,1.0,21.0,3.0,20000.0,...,2018,0,0,0,0,0,0,0,0,1
4,28195.0,38780.0,4841.0,3829.0,988.0,256,4.0,6.0,2.0,-644.0,...,2018,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95657,89881.0,96668.0,4841.0,3829.0,3078.0,256,4.0,6.0,2.0,-1000.0,...,2019,0,0,1,0,0,0,0,0,0
95658,91597.0,3503.0,3439.0,2643.0,3874.0,256,6.0,10.0,3.0,1000.0,...,2019,1,0,0,0,0,0,0,0,0
95659,82501.0,118602.0,4841.0,3829.0,3874.0,256,4.0,6.0,2.0,-20.0,...,2019,0,0,1,0,0,0,0,0,0
95660,136354.0,70924.0,1346.0,652.0,1709.0,256,6.0,19.0,3.0,3000.0,...,2019,0,0,0,0,0,0,0,1,0
95661,35670.0,29317.0,4841.0,3829.0,1709.0,256,4.0,6.0,2.0,-60.0,...,2019,0,0,1,0,0,0,0,0,0

In [15]:
normalize(data,["Amount", 
    "Value", 
    "PricingStrategy", 
    "FraudResult", 
    "ProductCategory_movies", 
    "ProductCategory_other", 
    "ProductCategory_transport", 
    "ProductCategory_tv", 
    "ProductCategory_utility_bill", 
    "ProductCategory_data_bundles"])

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,CountryCode,ProviderId,ProductId,ChannelId,Amount,...,transaction_year,ProductCategory_airtime,ProductCategory_data_bundles,ProductCategory_financial_services,ProductCategory_movies,ProductCategory_other,ProductCategory_ticket,ProductCategory_transport,ProductCategory_tv,ProductCategory_utility_bill
0,76871.0,36123.0,3957.0,887.0,4406.0,256,6.0,10.0,3.0,0.092004,...,2018,1,0.0,0,0.0,0.0,0,0.0,0.0,0.0
1,73770.0,15642.0,4841.0,3829.0,4406.0,256,4.0,6.0,2.0,0.091910,...,2018,0,0.0,1,0.0,0.0,0,0.0,0.0,0.0
2,26203.0,53941.0,4229.0,222.0,4683.0,256,6.0,1.0,3.0,0.091958,...,2018,1,0.0,0,0.0,0.0,0,0.0,0.0,0.0
3,380.0,102363.0,648.0,2185.0,988.0,256,1.0,21.0,3.0,0.093750,...,2018,0,0.0,0,0.0,0.0,0,0.0,0.0,1.0
4,28195.0,38780.0,4841.0,3829.0,988.0,256,4.0,6.0,2.0,0.091853,...,2018,0,0.0,1,0.0,0.0,0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95657,89881.0,96668.0,4841.0,3829.0,3078.0,256,4.0,6.0,2.0,0.091820,...,2019,0,0.0,1,0.0,0.0,0,0.0,0.0,0.0
95658,91597.0,3503.0,3439.0,2643.0,3874.0,256,6.0,10.0,3.0,0.092004,...,2019,1,0.0,0,0.0,0.0,0,0.0,0.0,0.0
95659,82501.0,118602.0,4841.0,3829.0,3874.0,256,4.0,6.0,2.0,0.091910,...,2019,0,0.0,1,0.0,0.0,0,0.0,0.0,0.0
95660,136354.0,70924.0,1346.0,652.0,1709.0,256,6.0,19.0,3.0,0.092188,...,2019,0,0.0,0,0.0,0.0,0,0.0,1.0,0.0
95661,35670.0,29317.0,4841.0,3829.0,1709.0,256,4.0,6.0,2.0,0.091906,...,2019,0,0.0,1,0.0,0.0,0,0.0,0.0,0.0

In [16]:
data.dtypes

TransactionId                                     float64
BatchId                                           float64
AccountId                                         float64
SubscriptionId                                    float64
CustomerId                                        float64
CountryCode                                         int64
ProviderId                                        float64
ProductId                                         float64
ChannelId                                         float64
Amount                                            float64
Value                                             float64
TransactionStartTime                  datetime64[ns, UTC]
PricingStrategy                                   float64
FraudResult                                       float64
total_transaction_amount                          float64
average_transaction_amount                        float64
transaction_count                                   int64
transaction_stddev                                float64
transaction_hour                                    int32
transaction_day                                     int32
transaction_month                                   int32
transaction_year                                    int32
ProductCategory_airtime                             int64
ProductCategory_data_bundles                      float64
ProductCategory_financial_services                  int64
ProductCategory_movies                            float64
ProductCategory_other                             float64
ProductCategory_ticket                              int64
ProductCategory_transport                         float64
ProductCategory_tv                                float64
ProductCategory_utility_bill                      float64
dtype: object

In [17]:
# apply_woe(data,['ProductCategory_utility_bill',
#     'Amount',
#     'Value',
#     'total_transaction_amount',
#     'average_transaction_amount',
#     'transaction_count',
#     'transaction_stddev',
#     'CountryCode',
#     'ProviderId',
#     'ChannelId',
#     'PricingStrategy',
#     'ProductCategory_airtime',
#     'ProductCategory_data_bundles',
#     'ProductCategory_financial_services',
#     'ProductCategory_movies',
#     'ProductCategory_other',
#     'ProductCategory_ticket',
#     'ProductCategory_transport'],"FraudResult")

In [19]:
calculate_rfms(data,"CustomerId","TransactionStartTime","Amount")

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,CountryCode,ProviderId,ProductId,ChannelId,Amount,...,ProductCategory_other,ProductCategory_ticket,ProductCategory_transport,ProductCategory_tv,ProductCategory_utility_bill,last_transaction_date,recency,frequency,monetary,rfms_score
0,76871.0,36123.0,3957.0,887.0,4406.0,256,6.0,10.0,3.0,0.092004,...,0.0,0,0.0,0.0,0.0,2019-02-12 10:24:40+00:00,0,119,10.947603,51.979041
1,73770.0,15642.0,4841.0,3829.0,4406.0,256,4.0,6.0,2.0,0.091910,...,0.0,0,0.0,0.0,0.0,2019-02-12 10:24:40+00:00,0,119,10.947603,51.979041
2,26203.0,53941.0,4229.0,222.0,4683.0,256,6.0,1.0,3.0,0.091958,...,0.0,0,0.0,0.0,0.0,2018-11-24 08:30:25+00:00,81,2,0.183915,17.073566
3,380.0,102363.0,648.0,2185.0,988.0,256,1.0,21.0,3.0,0.093750,...,0.0,0,0.0,0.0,1.0,2019-02-08 07:53:33+00:00,5,38,3.513670,17.605468
4,28195.0,38780.0,4841.0,3829.0,988.0,256,4.0,6.0,2.0,0.091853,...,0.0,0,0.0,0.0,0.0,2019-02-08 07:53:33+00:00,5,38,3.513670,17.605468
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95657,89881.0,96668.0,4841.0,3829.0,3078.0,256,4.0,6.0,2.0,0.091820,...,0.0,0,0.0,0.0,0.0,2019-02-13 09:54:09+00:00,0,573,52.889535,250.355814
95658,91597.0,3503.0,3439.0,2643.0,3874.0,256,6.0,10.0,3.0,0.092004,...,0.0,0,0.0,0.0,0.0,2019-02-13 09:54:35+00:00,0,43,3.957583,18.783033
95659,82501.0,118602.0,4841.0,3829.0,3874.0,256,4.0,6.0,2.0,0.091910,...,0.0,0,0.0,0.0,0.0,2019-02-13 09:54:35+00:00,0,43,3.957583,18.783033
95660,136354.0,70924.0,1346.0,652.0,1709.0,256,6.0,19.0,3.0,0.092188,...,0.0,0,0.0,1.0,0.0,2019-02-13 10:01:28+00:00,0,524,48.240072,228.896029
95661,35670.0,29317.0,4841.0,3829.0,1709.0,256,4.0,6.0,2.0,0.091906,...,0.0,0,0.0,0.0,0.0,2019-02-13 10:01:28+00:00,0,524,48.240072,228.896029

In [20]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95662 entries, 0 to 95661
Data columns (total 36 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   TransactionId                       95662 non-null  float64
 1   BatchId                             95662 non-null  float64
 2   AccountId                           95662 non-null  float64
 3   SubscriptionId                      95662 non-null  float64
 4   CustomerId                          95662 non-null  float64
 5   CountryCode                         95662 non-null  int64
 6   ProviderId                          95662 non-null  float64
 7   ProductId                           95662 non-null  float64
 8   ChannelId                           95662 non-null  float64
 9   Amount                              95662 non-null  float64
 10  Value                               95662 non-null  float64
 11  TransactionStartTime                95662 non-null  datetime64[ns, UTC]
 12  PricingStrategy                     95662 non-null  float64
 13  FraudResult                         95662 non-null  float64
 14  total_transaction_amount            95662 non-null  float64
 15  average_transaction_amount          95662 non-null  float64
 16  transaction_count                   95662 non-null  int64
 17  transaction_stddev                  94950 non-null  float64
 18  transaction_hour                    95662 non-null  int32
 19  transaction_day                     95662 non-null  int32
 20  transaction_month                   95662 non-null  int32
 21  transaction_year                    95662 non-null  int32
 22  ProductCategory_airtime             95662 non-null  int64
 23  ProductCategory_data_bundles        95662 non-null  float64
 24  ProductCategory_financial_services  95662 non-null  int64
 25  ProductCategory_movies              95662 non-null  float64
 26  ProductCategory_other               95662 non-null  float64
 27  ProductCategory_ticket              95662 non-null  int64
 28  ProductCategory_transport           95662 non-null  float64
 29  ProductCategory_tv                  95662 non-null  float64
 30  ProductCategory_utility_bill        95662 non-null  float64
 31  last_transaction_date               95662 non-null  datetime64[ns, UTC]
 32  recency                             95662 non-null  int64
 33  frequency                           95662 non-null  int64
 34  monetary                            95662 non-null  float64
 35  rfms_score                          95662 non-null  float64
dtypes: datetime64[ns, UTC](2), float64(23), int32(4), int64(7)
memory usage: 24.8 MB

In [23]:
data.to_csv("feature_eng.csv")